// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://papgwyidrketbanztnzk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcGd3eWlkcmtldGJhbnp0bnprIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTIzMDQxMzAsImV4cCI6MjA2Nzg4MDEzMH0.QJReD53V_jLSfM3wIuJ8Y3oDDAGEy-KeRcU4p4q5-zM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});